#!/usr/bin/env python3

'''
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
'''

from helpers.eulerMath import isEven
from helpers.generators import fibonacci


def solve():
    fib = fibonacci()
    sum = 0
    while True:
        i = next(fib)
        if i > 4000000:
            break
        if isEven(i):
            sum += i
    return sum


if __name__ == "__main__":
    print(solve())
